apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: web-server
  ports:
    - name: nginx 
      protocol: 'TCP'
      port: 80
      targetPort: 80    
  type: LoadBalancer